# Generated by Django 3.2.9 on 2022-02-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='sno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
